apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapi
  namespace: rahul
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: adminapi
          image: 'nginx'
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '500Mi'
              cpu: '200m'
            limits:
              memory: '1000Mi'
              cpu: '500m'

---

apiVersion: v1
kind: Service
metadata:
  name: adminapi
  namespace: rahul
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80

